import keyMirror from 'key-mirror';

module.exports = keyMirror({
	SEND_DATA_SUCCESS_ADD_MATER: null,
	GET_ERROR_ADD_MATER: null,
	REJECT_STATUS_ADD_MATER: null,
	UPDATE_PAYLOAD_ADD_MATER: null,
	UPDATE_MATER_NAME_ADD_MATER: null,
	CHANGE_TEST_ADD_MATER: null,
	GET_SECTIONS_SUCCESS_ADD_MATER: null,
	UPDATE_BUSINESS_ADD_MATER: null,
	SELECT_SECTION_ADD_MATER: null,
	UPDATE_AUTHOR_ADD_MATER: null,
	UPDATE_CODE_ADD_MATER: null,
	UPDATE_TYPE_ADD_MATER: null,
	UPDATE_ORIENTATION_ADD_MATER: null,
	UPDATE_DOWNLOAD_ADD_MATER: null,
	GET_MATERIAL_TYPE_ADD_MATER: null,
	REJECT_DATA_ADD_MATER: null
});
