import keyMirror from 'key-mirror';

module.exports = keyMirror({
	GET_DATA_ERROR_ENT_TEST: null,
	GET_TESTS_SUCCESS_ENT_TEST: null,
	SELECT_TESTS_ENT_TEST: null,
	GET_EVENTS_SUCCESS_ENT_TEST: null,
	SELECT_EVENTS_ENT_TEST: null,
	CHANGE_DATE_ENT_TEST: null,
	GET_COLLABS_SUCCESS_ENT_TEST: null,
	SELECT_COLLABS_ENT_TEST: null,
	SUBMIT_ENT_TEST: null,
	REJECT_STATUS_ENT_TEST: null,
	ADD_SCORE_ENT_TEST: null
});