import keyMirror from 'key-mirror';

module.exports = keyMirror({
	SEND_DATA_NEW_ADAPT: null,
	SEND_DATA_SUCCESS_NEW_ADAPT: null,
	GET_ERROR_NEW_ADAPT: null,
	REJECT_STATUS_NEW_ADAPT: null,
	UPDATE_START_DATE_NEW_ADAPT: null,
	UPDATE_END_DATE_NEW_ADAPT: null,
	UPDATE_FORM_NEW_ADAPT: null,
	REJECT_DATA_NEW_ADAPT: null,
	UPDATE_PAYLOAD_NEW_ADAPT: null,
	GET_COLLABS_SUCCESS_NEW_ADAPT: null,
	SELECT_COLLAB_NEW_ADAPT: null,
	SELECT_HR_NEW_ADAPT: null,
	SELECT_MANAGER_NEW_ADAPT: null,
	SELECT_TUTOR_NEW_ADAPT: null,
	GET_ADAPTS_SUCCESS_NEW_ADAPT: null,
	SELECT_ADAPT_NEW_ADAPT: null,
	SELECT_TUTOR_SEC_NEW_ADAPT: null,
	SELECT_HR_SEC_NEW_ADAPT: null
});
