import keyMirror from 'key-mirror';

module.exports = keyMirror({
	CHECK_NOTIF_EVENT: null,
	SEND_DATA_NOTIF_EVENT: null,
	SEND_DATA_SUCCESS_NOTIF_EVENT: null,
	SEND_DATA_ERROR_NOTIF_EVENT: null,
	REJECT_STATUS_NOTIF_EVENT: null,
	GET_DATA_SUCCESS_NOTIF_EVENT: null,
	GET_DATA_ERROR_NOTIF_EVENT: null,
	UPDATE_ITEM_NOTIF_EVENT: null,
	UPDATE_REASON_NOTIF_EVENT: null,
	UPDATE_DATE_NOTIF_EVENT: null
});
