import keyMirror from 'key-mirror';

module.exports = keyMirror({
	GET_DATA_ERROR_PURP_COURSE: null,
	GET_COURSE_SUCCESS_PURP_COURSE: null,
	SELECT_COURSE_PURP_COURSE: null,
	GET_EVENTS_SUCCESS_PURP_COURSE: null,
	SELECT_EVENTS_PURP_COURSE: null,
	CHANGE_DATE_PURP_COURSE: null,
	GET_COLLABS_SUCCESS_PURP_COURSE: null,
	SELECT_COLLABS_PURP_COURSE: null,
	SUBMIT_PURP_COURSE: null,
	REJECT_STATUS_PURP_COURSE: null
});
