import keyMirror from 'key-mirror';

module.exports = keyMirror({
	CHANGE_THEMATIC_STUDY_DEV: null,
	CHANGE_FORMAT_STUDY_DEV: null,
	CHANGE_BUISNES_STUDY_DEV: null,
	CHANGE_PURPOSE_STUDY_DEV: null,
	CHANGE_RESULT_STUDY_DEV: null,
	CHANGE_NUM_STUDY_DEV: null,
	CHANGE_POSITIONS_STUDY_DEV: null,
	UPDATE_START_DATE_STUDY_DEV: null,
	UPDATE_END_DATE_STUDY_DEV: null,
	ADD_COMMENT_STUDY_DEV: null,
	CHANGE_PRED_TEST_STUDY_DEV: null,
	CHANGE_POST_TEST_STUDY_DEV: null,
	CHANGE_PROFILE_STUDY_DEV: null,
	POST_DATA_ERROR: null,
	REJECT_STATUS: null,
	ACTION_SUCCESS: null,
	GET_REGIONS_STUDY_DEV: null,
	CHANGE_REGION_STUDY_DEV: null
});