import keyMirror from 'key-mirror';

module.exports = keyMirror({
	POST_DATA_ERROR: null,
	ACTION_SUCCESS: null,
	GET_SUCCESS_TR_PROG: null,
	CHANGE_START_TIME_TR_PROG: null,
	CHANGE_END_TIME_TR_PROG: null,
	CHANGE_PROG_TR_PROG: null,
	CHANGE_FORM_TR_PROG: null,
	UPDATE_START_DATE_TR_PROG: null,
	CHANGE_TOWN_TR_PROG: null,
	CHANGE_COMMENT_TR_PROG: null,
	REJECT_STATUS_TR_PROG: null,
	UPDATE_POSITIONS_TR_PROG: null,
	UPDATE_PLACE_TR_PROG: null
});
