import keyMirror from 'key-mirror';

module.exports = keyMirror({
	CHECK_EXCL_COLLAB: null,
	SEND_DATA_EXCL_COLLAB: null,
	SEND_DATA_SUCCESS_EXCL_COLLAB: null,
	SEND_DATA_ERROR_EXCL_COLLAB: null,
	REJECT_STATUS_EXCL_COLLAB: null,
	GET_DATA_SUCCESS_EXCL_COLLAB: null,
	GET_DATA_ERROR_EXCL_COLLAB: null,
	UPDATE_ITEM_EXCL_COLLAB: null,
	UPDATE_REASON_EXCL_COLLAB: null,
	UPDATE_DATE_EXCL_COLLAB: null
});